[build]
  base = "frontend"
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ../backend"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm dev"
  framework = "next"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://quizprobynova-backend.onrender.com"
