services:
  - type: web
    name: quizpro-bynova-backend
    env: node
    plan: starter
    region: oregon
    rootDirectory: backend
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: node dist/index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: quizpro-db
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_PROVIDER
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

databases:
  - name: quizpro-db
    databaseName: quizpro
    plan: starter
    region: oregon
