name: Deploy
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'production'
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Frontend build & deploy to Netlify (runs Netlify build with Next plugin)
      - name: Install frontend deps
        run: pnpm install --frozen-lockfile
        working-directory: frontend
      - name: Deploy to Netlify (build with plugin)
        uses: netlify/actions/cli@v4.3.1
        with:
          args: deploy --build --prod --cwd frontend --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Backend deploy to Render (build happens on Render)
      - name: Trigger Render deploy
        uses: jpvillanueva/trigger-render-deploy@v1.4.3
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
